/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <nauty.h>
/* Header for class de_hhu_bsinfo_dxgraph_algo_isomorphy_JNINauty */

#ifndef _Included_de_hhu_bsinfo_dxgraph_algo_isomorphy_JNINauty
#define _Included_de_hhu_bsinfo_dxgraph_algo_isomorphy_JNINauty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_dxgraph_algo_isomorphy_JNINauty
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_dxgraph_algo_isomorphy_JNINauty_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_hhu_bsinfo_dxgraph_algo_isomorphy_JNINauty
 * Method:    addEdge
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_dxgraph_algo_isomorphy_JNINauty_addEdge
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     de_hhu_bsinfo_dxgraph_algo_isomorphy_JNINauty
 * Method:    checkIsomorpy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_hhu_bsinfo_dxgraph_algo_isomorphy_JNINauty_checkIsomorpy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
